### ISSUE TITLE
Problem: can't see the Specs of Smart Contract Specs

### ISSUE THREAD

**Issue by matthewvogas** [Hoosling/smart-contracts#4]
sub of
- #1

**Comment by lmontero18** [comment]
Added specs page for the hoosling smart contracts repo.
@matthewvogas waiting for your review.

**Comment by matthewvogas** [comment]
@MY-RV @sfabricito pls review too

**Comment by matthewvogas** [comment]
pls provie more information abot chains, cryptos, layers, rewards, in the specs, can take some inspiration with https://thegraph.com/, provide more info about the stack, solidity, libraries, etc... and logical teck structure.

Start creating the smart contract and adding the 0x into the specs too

**Comment by matthewvogas** [comment]
this info need to be in the specs too

![Screenshot 2024-11-26 at 9 19 06 PM](https://github.com/user-attachments/assets/885ad1af-599b-4765-858a-f5420883c947)

https://thegraph.com/docs/en/quick-start/

@lmontero18

**Comment by matthewvogas** [comment]
pls create tesnet sepolia wallet for test and ping me, I can send $800 eth sepolia in that testnet wallet to start

**Comment by lmontero18** [comment]
> pls create tesnet sepolia wallet for test and ping me, I can send $800 eth sepolia in that testnet wallet to start

Why do we need that wallet

> this info need to be in the specs too
> 
> ![Screenshot 2024-11-26 at 9 19 06 PM](https://private-user-images.githubusercontent.com/151702554/390243852-885ad1af-599b-4765-858a-f5420883c947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzgzMDAsIm5iZiI6MTczMjY3ODAwMCwicGF0aCI6Ii8xNTE3MDI1NTQvMzkwMjQzODUyLTg4NWFkMWFmLTU5OWItNDc2NS04NThhLWY1NDIwODgzYzk0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMzI2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjIzMzM3MWNjMmExZTIwZDc3NDZlZWMwY2MwYWM5NTk0MDQ2YWVhODQxZGRiZWJlNThmN2EzMjU4NDYxNmQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gIPUpzpQdijENBRqHCr4GA-XxtBymOZTbBNEiQz9VXw)
> 
> https://thegraph.com/docs/en/quick-start/
> 
> @lmontero18

Me and @sfabricito are going to have a talk about this, but first, we need to understand what we really need for the contracts to work correctly, then we add that kind of information to the specs page.

**Comment by matthewvogas** [comment]
@lmontero18 is this done? if can you close it so?

**Comment by lmontero18** [comment]
Im modifying the specs file, so its not done yet!

**Comment by lmontero18** [comment]
> pls provie more information abot chains, cryptos, layers, rewards, in the specs, can take some inspiration with https://thegraph.com/, provide more info about the stack, solidity, libraries, etc... and logical teck structure.
> 
> Start creating the smart contract and adding the 0x into the specs too

Also, thegraph is something that @MY-RV is going to use, it is not use in the creation of smart contracts, this can be added in the specs of the backend repository.

**Comment by lmontero18** [comment]
@matthewvogas, @sfabricito, @MY-RV  already change to a new version of the specs file for the smart contracts, look at it and give me some feedback!

**Comment by matthewvogas** [comment]
@sfabricito @lmontero18 @MY-RV I'll close this issue cause now we have the specs, so only let's keep the specs up-to-date weekly
